remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Foundations of Computational Psychiatry
description: >- # this means to ignore newlines until "baseurl:"
  MSSM BSR 2708 01 Foundations of Computational Psychiatry